### ISSUE TITLE
No such file or directory: 'datasets/icdar2013/test_gts/gt_img_224.txt'

### ISSUE THREAD

**Issue by yijieluo** [MhLiao/MaskTextSpotter#42]
作者您好，我在执行sh test.sh的过程中，发生了如下错误。icdar2013数据集是在您给的网盘地址下载的，并且解压到了datasets文件夹下。

Traceback (most recent call last):
  File "tools/test_net.py", line 95, in <module>
    main()
  File "tools/test_net.py", line 89, in main
    cfg=cfg,
  File "/home/luoyijie/MaskTextSpotter/maskrcnn_benchmark/engine/text_inference.py", line 380, in inference
    predictions = compute_on_dataset(model, data_loader, device)
  File "/home/luoyijie/MaskTextSpotter/maskrcnn_benchmark/engine/text_inference.py", line 55, in compute_on_dataset
    for i, batch in tqdm(enumerate(data_loader)):
  File "/home/luoyijie/anaconda3/envs/masktextspotter/lib/python3.7/site-packages/tqdm/std.py", line 1102, in __iter__
    for obj in iterable:
  File "/home/luoyijie/anaconda3/envs/masktextspotter/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/luoyijie/anaconda3/envs/masktextspotter/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/luoyijie/anaconda3/envs/masktextspotter/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/luoyijie/anaconda3/envs/masktextspotter/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/luoyijie/anaconda3/envs/masktextspotter/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/luoyijie/anaconda3/envs/masktextspotter/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/luoyijie/MaskTextSpotter/maskrcnn_benchmark/data/datasets/icdar.py", line 32, in __getitem__
    words,boxes,charsbbs,segmentations=self.load_gt_from_txt(gt_path,height,width)
  File "/home/luoyijie/MaskTextSpotter/maskrcnn_benchmark/data/datasets/icdar.py", line 89, in load_gt_from_txt
    lines = open(gt_path).readlines()
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/icdar2013/test_gts/gt_img_224.txt'

**Comment by arthurchanhokman** [comment]
We are having the same problem. Thanks

**Comment by arthurchanhokman** [comment]
Please check issue #9 
[https://github.com/MhLiao/MaskTextSpotter/issues/9](url)
Cheers
