### ISSUE TITLE
RuntimeError: _th_or not supported on CUDAType for Bool

### ISSUE THREAD

**Issue by tangtangqin** [MhLiao/MaskTextSpotter#67]
On ubuntu16.04, cuda9.0, there is a running error, do not know how to modify it?
Traceback (most recent call last):
  File "tools / train_net.py", line 173, in <module>
    main ()
  File "tools / train_net.py", line 166, in main
    model = train (cfg, args.local_rank, args.distributed)
  File "tools / train_net.py", line 76, in train
    cfg,
  File "/home/f5100/MaskTextSpotter/maskrcnn_benchmark/engine/trainer.py", line 66, in do_train
    loss_dict = model (images, targets)
  File "/home/f5100/anaconda3/envs/masktextspotter/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward (* input, ** kwargs)
  File "/home/f5100/MaskTextSpotter/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 52, in forward
    x, result, detector_losses = self.roi_heads (features, proposals, targets)
  File "/home/f5100/anaconda3/envs/masktextspotter/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward (* input, ** kwargs)
  File "/home/f5100/MaskTextSpotter/maskrcnn_benchmark/modeling/roi_heads/roi_heads.py", line 23, in forward
    x, detections, loss_box = self.box (features, proposals, targets)
  File "/home/f5100/anaconda3/envs/masktextspotter/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward (* input, ** kwargs)
  File "/home/f5100/MaskTextSpotter/maskrcnn_benchmark/modeling/roi_heads/box_head/box_head.py", line 42, in forward
    proposals = self.loss_evaluator.subsample (proposals, targets)
  File "/home/f5100/MaskTextSpotter/maskrcnn_benchmark/modeling/roi_heads/box_head/loss.py", line 104, in subsample
    img_sampled_inds = torch.nonzero (pos_inds_img | neg_inds_img) .squeeze (1)
RuntimeError: _th_or not supported on CUDAType for Bool

**Comment by MhLiao** [comment]
@tangtangqin I think this is related to the Pytorch version.
