### ISSUE TITLE
Finetune [ValueError: Type mismatch] + [returned non-zero exit status 1.]

### ISSUE THREAD

**Issue by ghost** [MhLiao/MaskTextSpotter#7]
@MhLiao 

When trying to Finetune using icdar2015, I get `returned non-zero exit status 1.` error:
```
python3 -m torch.distributed.launch --nproc_per_node=1 tools/train_net.py --config-file configs/finetune.yaml
```

The terminal log:
```
(mask) home@home-desktop:~/p5/MaskTextSpotter$ python3 -m torch.distributed.launch --nproc_per_node=1 tools/train_net.py --config-file configs/finetune.yaml
Traceback (most recent call last):
  File "tools/train_net.py", line 173, in <module>
    main()
  File "tools/train_net.py", line 145, in main
    cfg.merge_from_file(args.config_file)
  File "/home/home/anaconda3/envs/mask/lib/python3.6/site-packages/yacs/config.py", line 213, in merge_from_file
    self.merge_from_other_cfg(cfg)
  File "/home/home/anaconda3/envs/mask/lib/python3.6/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/home/anaconda3/envs/mask/lib/python3.6/site-packages/yacs/config.py", line 460, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/home/anaconda3/envs/mask/lib/python3.6/site-packages/yacs/config.py", line 456, in _merge_a_into_b
    v = _check_and_coerce_cfg_value_type(v, b[k], k, full_key)
  File "/home/home/anaconda3/envs/mask/lib/python3.6/site-packages/yacs/config.py", line 513, in _check_and_coerce_cfg_value_type
    original_type, replacement_type, original, replacement, full_key
ValueError: Type mismatch (<class 'tuple'> vs. <class 'str'>) with values (() vs. icdar_2015_train) for config key: DATASETS.TRAIN
Traceback (most recent call last):
  File "/home/home/anaconda3/envs/mask/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/home/anaconda3/envs/mask/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/home/anaconda3/envs/mask/lib/python3.6/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/home/home/anaconda3/envs/mask/lib/python3.6/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/home/anaconda3/envs/mask/bin/python3', '-u', 'tools/train_net.py', '--local_rank=0', '--config-file', 'configs/finetune.yaml']' returned non-zero exit status 1.
```

**Comment by ghost** [comment]
hmmm... I deleted the MaskTextSpotter folder, the i cloned the repository again, then it workd
